// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CHASSIS_H
#define CHASSIS_H

#include "Commands/Subsystem.h"
#include "ctre/Phoenix.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Chassis: public frc::Subsystem {
private:
  static const char kSubsystemName[];
  static std::shared_ptr<Chassis> self;

  std::shared_ptr<WPI_TalonSRX> left1Wheel;
	std::shared_ptr<WPI_TalonSRX> left2Wheel;
	std::shared_ptr<WPI_TalonSRX> right1Wheel;
	std::shared_ptr<WPI_TalonSRX> right2Wheel;

public:
	static std::shared_ptr<Chassis> getInstance();
	Chassis();

	void SetTankDrive(double left, double right);
	void InitDefaultCommand();
};

#endif
