// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CHASSIS_H
#define CHASSIS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Commands/TankDrive.h"


/**
 *
 *
 * @author ExampleAuthor
 */
class Chassis: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<WPI_TalonSRX> left1Wheel;
	static std::shared_ptr<WPI_TalonSRX> left2Wheel;
	static std::shared_ptr<WPI_TalonSRX> right1Wheel;
	static std::shared_ptr<WPI_TalonSRX> right2Wheel;

public:
	static std::shared_ptr<Chassis> getInstance;
	Chassis();
	void SetTankDrive(double left, double right);
	void InitDefaultCommand();
};

#endif
