// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::chassisright1Wheel;
std::shared_ptr<CANTalon> RobotMap::chassisright2Wheel;
std::shared_ptr<CANTalon> RobotMap::chassisleft1Wheel;
std::shared_ptr<CANTalon> RobotMap::chassisleft2Wheel;
std::shared_ptr<CANTalon> RobotMap::intakeleftIntake;
std::shared_ptr<CANTalon> RobotMap::intakerightIntake;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    chassisright1Wheel.reset(new CANTalon(0));
    lw->AddActuator("Chassis", "right1Wheel", chassisright1Wheel);
    
    chassisright2Wheel.reset(new CANTalon(1));
    lw->AddActuator("Chassis", "right2Wheel", chassisright2Wheel);
    
    chassisleft1Wheel.reset(new CANTalon(2));
    lw->AddActuator("Chassis", "left1Wheel", chassisleft1Wheel);
    
    chassisleft2Wheel.reset(new CANTalon(3));
    lw->AddActuator("Chassis", "left2Wheel", chassisleft2Wheel);
    
    intakeleftIntake.reset(new CANTalon(4));
    lw->AddActuator("Intake", "leftIntake", intakeleftIntake);
    
    intakerightIntake.reset(new CANTalon(5));
    lw->AddActuator("Intake", "rightIntake", intakerightIntake);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
