#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around
 */
class RobotMap {
public:

//..........Motors..........

  //..........Chassis..........
	  static const int kIDRight1Wheel = 2;//should be 1 on practice bot
	  static const int kIDRight2Wheel = 1;//should be 2 on practice bot
	  static const int kIDLeft1Wheel = 3;
	  static const int kIDLeft2Wheel = 4;
	//..........Intake..........
	  static const int kIDIntakeMotorTop = 5;
	  static const int kIDIntakeMotorBottom = 8;
	  static const int kIDBanner = 1;
	//..........Arm..........
	  static const int kIDLeftArm = 10;
	  static const int kIDRightArm = 9;
	//.........Sling.........
	  static const int kIDPullSling = 7;

	//........Climber.............
	  static const int kIDClimber = 6;

//..........Solenoids..........

	  static const int kIDRampForward = 0;
	  static const int kIDRampReverse = 7;

	  static const int kIDIntakeForward = 1;

	  static const int kIDIntakeReverse = 6;

    static const int kIDSlingForward = 3;
    static const int kIDSlingReverse = 4;

    static const int kIDBrakeForward = 2;
    static const int kIDBrakeReverse = 5;

	//........Analog Inputs...........
	  static const int kIDArmPot = 0;

	  static void init();
};

// TODO Refactor to a constants.h?

// See TalanSRX::ConfigSelectedFeedbackSensor() pidIdx
static const int kPID_PrimaryClosedLoop = 0;
static const int kPID_CascadedClosedLoop = 1;

// See TalanSRX::ConfigSelectedFeedbackSensor() timoutMs
static const int kTimeout_DontBlock = 0;
static const int kTimeout_10Millis = 10;

static const int kSlot0 = 0;
static const int kSlot1 = 1;

#endif
